# Prediction algorithms

This notebook is to analyse the energy data and come up with more conclusion

In [28]:
#Importing Libraries
import matplotlib.pyplot as plt
import pandas as pd
import time
import numpy as np
import seaborn as sns
import datetime
import math


from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

%matplotlib inline

### Load Data

In [29]:
data= pd.read_csv("./Dataset/new_data_feature.csv")

In [30]:
data.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,rv1,rv2,date_time,dayoftheweek,WeekDayType,timeofDay,activeStatus,NSM,weekOfTheYear,season
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,13.275433,13.275433,2016-01-11 17:00:00,Monday,Weekday,Day,awake,61200,2,winter
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,18.606195,18.606195,2016-01-11 17:10:00,Monday,Weekday,Day,awake,61800,2,winter
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,28.642668,28.642668,2016-01-11 17:20:00,Monday,Weekday,Day,awake,62400,2,winter
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,45.410389,45.410389,2016-01-11 17:30:00,Monday,Weekday,Day,awake,63000,2,winter
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,10.084097,10.084097,2016-01-11 17:40:00,Monday,Weekday,Day,awake,63600,2,winter

<h6>Variable Description<br />
====================</h6>

<ul>
	<li>date time year-month-day hour:minute:second&nbsp;</li>
	<li>Appliances, energy use in Wh</li>
	<li>lights, energy use of light fixtures in the house in Wh</li>
	<li>T1, Temperature in kitchen area, in Celsius</li>
	<li>RH_1, Humidity in kitchen area, in %</li>
	<li>T2, Temperature in living room area, in Celsius</li>
	<li>RH_2, Humidity in living room area, in %</li>
	<li>T3, Temperature in laundry room area</li>
	<li>RH_3, Humidity in laundry room area, in %</li>
	<li>T4, Temperature in office room, in Celsius</li>
	<li>RH_4, Humidity in office room, in %</li>
	<li>T5, Temperature in bathroom, in Celsius</li>
	<li>RH_5, Humidity in bathroom, in %</li>
	<li>T6, Temperature outside the building (north side), in Celsius</li>
	<li>RH_6, Humidity outside the building (north side), in %</li>
	<li>T7, Temperature in ironing room , in Celsius</li>
	<li>RH_7, Humidity in ironing room, in %</li>
	<li>T8, Temperature in teenager room 2, in Celsius</li>
	<li>RH_8, Humidity in teenager room 2, in %</li>
	<li>T9, Temperature in parents room, in Celsius</li>
	<li>RH_9, Humidity in parents room, in %</li>
	<li>To, Temperature outside (from Chi&egrave;vres weather station), in Celsius</li>
	<li>Pressure (from Chi&egrave;vres weather station), in mm Hg</li>
	<li>RH_out, Humidity outside (from Chi&egrave;vres weather station), in %</li>
	<li>Windspeed (from Chi&egrave;vres weather station), in m/s</li>
	<li>Visibility (from Chi&egrave;vres weather station), in km</li>
	<li>Tdewpoint (from Chi&egrave;vres weather station), &deg;C</li>
	<li>rv1, Random variable 1, nondimensional</li>
	<li>rv2, Rnadom variable 2, nondimensional</li>
</ul>

<p>Where indicated, data from the nearest airport weather station (Chi&egrave;vres Airport, Belgium) was downloaded from a public data set from&nbsp;</p>

<p>Reliable Prognosis, rp5.ru. Permission was obtained from Reliable Prognosis for the distribution of the 4 months of data.<br />
&nbsp;</p>

In [31]:
data.shape

(19735, 37)

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 37 columns):
date             19735 non-null object
Appliances       19735 non-null int64
lights           19735 non-null int64
T1               19735 non-null float64
RH_1             19735 non-null float64
T2               19735 non-null float64
RH_2             19735 non-null float64
T3               19735 non-null float64
RH_3             19735 non-null float64
T4               19735 non-null float64
RH_4             19735 non-null float64
T5               19735 non-null float64
RH_5             19735 non-null float64
T6               19735 non-null float64
RH_6             19735 non-null float64
T7               19735 non-null float64
RH_7             19735 non-null float64
T8               19735 non-null float64
RH_8             19735 non-null float64
T9               19735 non-null float64
RH_9             19735 non-null float64
T_out            19735 non-null float64
Press_mm_hg      19735 non-null float64
RH_out           19735 non-null float64
Windspeed        19735 non-null float64
Visibility       19735 non-null float64
Tdewpoint        19735 non-null float64
rv1              19735 non-null float64
rv2              19735 non-null float64
date_time        19735 non-null object
dayoftheweek     19735 non-null object
WeekDayType      19735 non-null object
timeofDay        19735 non-null object
activeStatus     19735 non-null object
NSM              19735 non-null int64
weekOfTheYear    19735 non-null int64
season           19735 non-null object
dtypes: float64(26), int64(4), object(7)
memory usage: 5.6+ MB

In [33]:
data.isnull().sum()

date             0
Appliances       0
lights           0
T1               0
RH_1             0
T2               0
RH_2             0
T3               0
RH_3             0
T4               0
RH_4             0
T5               0
RH_5             0
T6               0
RH_6             0
T7               0
RH_7             0
T8               0
RH_8             0
T9               0
RH_9             0
T_out            0
Press_mm_hg      0
RH_out           0
Windspeed        0
Visibility       0
Tdewpoint        0
rv1              0
rv2              0
date_time        0
dayoftheweek     0
WeekDayType      0
timeofDay        0
activeStatus     0
NSM              0
weekOfTheYear    0
season           0
dtype: int64

We can conclud that there is no missing values here.

In [34]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Appliances,19735.0,97.694958,102.524891,10.000000,50.000000,60.000000,100.000000,1080.000000
lights,19735.0,3.801875,7.935988,0.000000,0.000000,0.000000,0.000000,70.000000
T1,19735.0,21.686571,1.606066,16.790000,20.760000,21.600000,22.600000,26.260000
RH_1,19735.0,40.259739,3.979299,27.023333,37.333333,39.656667,43.066667,63.360000
T2,19735.0,20.341219,2.192974,16.100000,18.790000,20.000000,21.500000,29.856667
RH_2,19735.0,40.420420,4.069813,20.463333,37.900000,40.500000,43.260000,56.026667
T3,19735.0,22.267611,2.006111,17.200000,20.790000,22.100000,23.290000,29.236000
RH_3,19735.0,39.242500,3.254576,28.766667,36.900000,38.530000,41.760000,50.163333
T4,19735.0,20.855335,2.042884,15.100000,19.530000,20.666667,22.100000,26.200000
RH_4,19735.0,39.026904,4.341321,27.660000,35.530000,38.400000,42.156667,51.090000
T5,19735.0,19.592106,1.844623,15.330000,18.277500,19.390000,20.619643,25.795000
RH_5,19735.0,50.949283,9.022034,29.815000,45.400000,49.090000,53.663333,96.321667
T6,19735.0,7.910939,6.090347,-6.065000,3.626667,7.300000,11.256000,28.290000
RH_6,19735.0,54.609083,31.149806,1.000000,30.025000,55.290000,83.226667,99.900000
T7,19735.0,20.267106,2.109993,15.390000,18.700000,20.033333,21.600000,26.000000
RH_7,19735.0,35.388200,5.114208,23.200000,31.500000,34.863333,39.000000,51.400000
T8,19735.0,22.029107,1.956162,16.306667,20.790000,22.100000,23.390000,27.230000
RH_8,19735.0,42.936165,5.224361,29.600000,39.066667,42.375000,46.536000,58.780000
T9,19735.0,19.485828,2.014712,14.890000,18.000000,19.390000,20.600000,24.500000
RH_9,19735.0,41.552401,4.151497,29.166667,38.500000,40.900000,44.338095,53.326667
T_out,19735.0,7.411665,5.317409,-5.000000,3.666667,6.916667,10.408333,26.100000
Press_mm_hg,19735.0,755.522602,7.399441,729.300000,750.933333,756.100000,760.933333,772.300000
RH_out,19735.0,79.750418,14.901088,24.000000,70.333333,83.666667,91.666667,100.000000
Windspeed,19735.0,4.039752,2.451221,0.000000,2.000000,3.666667,5.500000,14.000000
Visibility,19735.0,38.330834,11.794719,1.000000,29.000000,40.000000,40.000000,66.000000
Tdewpoint,19735.0,3.760707,4.194648,-6.600000,0.900000,3.433333,6.566667,15.500000
rv1,19735.0,24.988033,14.496634,0.005322,12.497889,24.897653,37.583769,49.996530
rv2,19735.0,24.988033,14.496634,0.005322,12.497889,24.897653,37.583769,49.996530
NSM,19735.0,42907.129465,24940.020831,0.000000,21600.000000,43200.000000,64200.000000,85800.000000
weekOfTheYear,19735.0,11.393615,5.657985,2.000000,6.000000,11.000000,16.000000,21.000000

In [35]:
data = pd.get_dummies(data, columns=["timeofDay","activeStatus",'dayoftheweek','WeekDayType','season'])

In [36]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Appliances,19735.0,97.694958,102.524891,10.000000,50.000000,60.000000,100.000000,1080.000000
lights,19735.0,3.801875,7.935988,0.000000,0.000000,0.000000,0.000000,70.000000
T1,19735.0,21.686571,1.606066,16.790000,20.760000,21.600000,22.600000,26.260000
RH_1,19735.0,40.259739,3.979299,27.023333,37.333333,39.656667,43.066667,63.360000
T2,19735.0,20.341219,2.192974,16.100000,18.790000,20.000000,21.500000,29.856667
RH_2,19735.0,40.420420,4.069813,20.463333,37.900000,40.500000,43.260000,56.026667
T3,19735.0,22.267611,2.006111,17.200000,20.790000,22.100000,23.290000,29.236000
RH_3,19735.0,39.242500,3.254576,28.766667,36.900000,38.530000,41.760000,50.163333
T4,19735.0,20.855335,2.042884,15.100000,19.530000,20.666667,22.100000,26.200000
RH_4,19735.0,39.026904,4.341321,27.660000,35.530000,38.400000,42.156667,51.090000
T5,19735.0,19.592106,1.844623,15.330000,18.277500,19.390000,20.619643,25.795000
RH_5,19735.0,50.949283,9.022034,29.815000,45.400000,49.090000,53.663333,96.321667
T6,19735.0,7.910939,6.090347,-6.065000,3.626667,7.300000,11.256000,28.290000
RH_6,19735.0,54.609083,31.149806,1.000000,30.025000,55.290000,83.226667,99.900000
T7,19735.0,20.267106,2.109993,15.390000,18.700000,20.033333,21.600000,26.000000
RH_7,19735.0,35.388200,5.114208,23.200000,31.500000,34.863333,39.000000,51.400000
T8,19735.0,22.029107,1.956162,16.306667,20.790000,22.100000,23.390000,27.230000
RH_8,19735.0,42.936165,5.224361,29.600000,39.066667,42.375000,46.536000,58.780000
T9,19735.0,19.485828,2.014712,14.890000,18.000000,19.390000,20.600000,24.500000
RH_9,19735.0,41.552401,4.151497,29.166667,38.500000,40.900000,44.338095,53.326667
T_out,19735.0,7.411665,5.317409,-5.000000,3.666667,6.916667,10.408333,26.100000
Press_mm_hg,19735.0,755.522602,7.399441,729.300000,750.933333,756.100000,760.933333,772.300000
RH_out,19735.0,79.750418,14.901088,24.000000,70.333333,83.666667,91.666667,100.000000
Windspeed,19735.0,4.039752,2.451221,0.000000,2.000000,3.666667,5.500000,14.000000
Visibility,19735.0,38.330834,11.794719,1.000000,29.000000,40.000000,40.000000,66.000000
Tdewpoint,19735.0,3.760707,4.194648,-6.600000,0.900000,3.433333,6.566667,15.500000
rv1,19735.0,24.988033,14.496634,0.005322,12.497889,24.897653,37.583769,49.996530
rv2,19735.0,24.988033,14.496634,0.005322,12.497889,24.897653,37.583769,49.996530
NSM,19735.0,42907.129465,24940.020831,0.000000,21600.000000,43200.000000,64200.000000,85800.000000
weekOfTheYear,19735.0,11.393615,5.657985,2.000000,6.000000,11.000000,16.000000,21.000000
timeofDay_Day,19735.0,0.500127,0.500013,0.000000,0.000000,1.000000,1.000000,1.000000
timeofDay_Night,19735.0,0.499873,0.500013,0.000000,0.000000,0.000000,1.000000,1.000000
activeStatus_awake,19735.0,0.583481,0.492994,0.000000,0.000000,1.000000,1.000000,1.000000
activeStatus_sleep,19735.0,0.416519,0.492994,0.000000,0.000000,0.000000,1.000000,1.000000
dayoftheweek_Friday,19735.0,0.144160,0.351261,0.000000,0.000000,0.000000,0.000000,1.000000
dayoftheweek_Monday,19735.0,0.140765,0.347788,0.000000,0.000000,0.000000,0.000000,1.000000
dayoftheweek_Saturday,19735.0,0.138637,0.345576,0.000000,0.000000,0.000000,0.000000,1.000000
dayoftheweek_Sunday,19735.0,0.138637,0.345576,0.000000,0.000000,0.000000,0.000000,1.000000
dayoftheweek_Thurday,19735.0,0.145934,0.353049,0.000000,0.000000,0.000000,0.000000,1.000000
dayoftheweek_Tuesday,19735.0,0.145934,0.353049,0.000000,0.000000,0.000000,0.000000,1.000000
dayoftheweek_Wednesday,19735.0,0.145934,0.353049,0.000000,0.000000,0.000000,0.000000,1.000000
WeekDayType_Weekday,19735.0,0.722726,0.447664,0.000000,0.000000,1.000000,1.000000,1.000000
WeekDayType_weekend,19735.0,0.277274,0.447664,0.000000,0.000000,0.000000,1.000000,1.000000
season_spring,19735.0,0.494401,0.499981,0.000000,0.000000,0.000000,1.000000,1.000000
season_winter,19735.0,0.505599,0.499981,0.000000,0.000000,1.000000,1.000000,1.000000

## Libraries, Functions and Variables to Evaluate model

In [37]:
#Importing Libraries
from sklearn.metrics import r2_score, mean_squared_error,mean_absolute_error
from sklearn.cross_validation import cross_val_score


rmse_dict = {}    
def rmse(correct,estimated):
    rmse_val = np.sqrt(mean_squared_error(correct,estimated)) 
    return rmse_val

# Generating the Table Frame for metrics
evluation_table = pd.DataFrame({  'Model_desc':[],
                        'Model_param':[],
                        'r2_train': [],
                        'r2_test': [],
                        'rms_train':[], 
                        'rms_test': [],
                        'mae_train': [],
                        'mae_test': [],
                        'mape_train':[],
                        'mape_test':[],
                        'cross_val_score' : []})


# Evaluating the model
def evaluate_model(model, model_desc,model_param, X_train, y_train, X_test, y_test):
    global evluation_table
    
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
        
    
    try:
        r2_train = r2_score(y_train, y_train_pred)
        r2_test = r2_score(y_test, y_test_pred)
    except:
        r2_train = "not calculated"
        r2_test = "not calculated"
    try:
        rms_train = rmse(y_train, y_train_pred)
        rms_test = rmse(y_test, y_test_pred)
    except:
        rms_train = "not calculated"
        rms_test = "not calculated"
    try:
        mae_train = mean_absolute_error(y_train, y_train_pred)
        mae_test = mean_absolute_error(y_test, y_test_pred)
    except:
        mae_train = "not calculated"
        mae_test = "not calculated"
    try:
        mape_train = np.mean(np.abs((y_train - y_train_pred) / y_train)) * 100
        mape_test = np.mean(np.abs((y_test - y_test_pred) / y_test)) * 100
    except:
        mape_train = "not calculated"
        mape_test = "not calculated"
    
    
#     try:
#         cv_score = cross_val_score(model, X_train, y_train, cv=10)
#         cv_score = cv_score.mean()
#     except:
#         cv_score = "Not calulated"
        
    model_param = pd.DataFrame({'Model_desc':[model_desc],
                            'Model_param':[model_param],
                            'r2_train': [r2_train],
                            'r2_test': [r2_test],
                            'rms_train':[rms_train], 
                            'rms_test': [rms_test],
                            'mae_train': [mae_train],
                            'mae_test': [mae_test],
                            'mape_train':[mape_train],
                            'mape_test':[mape_test],
                            'cross_val_score' : "Not Calculated"})

    evluation_table = evluation_table.append([model_param])
 
    return evluation_table

### Linear Regression

In [38]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model

In [39]:
#Select response y and Training set X
k = list(data)
k
my_cols = [
 'lights',
 'T1',
 'RH_1',
 'T2',
 'RH_2',
 'T3',
 'RH_3',
 'T4',
 'RH_4',
 'T5',
 'RH_5',
 'T6',
 'RH_6',
 'T7',
 'RH_7',
 'T8',
 'RH_8',
 'T9',
 'RH_9',
 'T_out',
 'Press_mm_hg',
 'RH_out',
 'Windspeed',
 'Visibility',
 'Tdewpoint',
 'NSM',
 'weekOfTheYear',
 'timeofDay_Day',
 'timeofDay_Night',
 'activeStatus_awake',
 'activeStatus_sleep',
 'dayoftheweek_Friday',
 'dayoftheweek_Monday',
 'dayoftheweek_Saturday',
 'dayoftheweek_Sunday',
 'dayoftheweek_Thurday',
 'dayoftheweek_Tuesday',
 'dayoftheweek_Wednesday',
 'WeekDayType_Weekday',
 'WeekDayType_weekend',
 'season_spring',
 'season_winter']
X = data[my_cols].values
y = data['Appliances']

In [40]:
#train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

In [41]:
lm = linear_model.LinearRegression()
linear = lm.fit(X_train, y_train)

In [42]:
evaluate_model(linear, "LinearRegression",linear,X_train,y_train, X_test , y_test)

,Model_desc,Model_param,cross_val_score,mae_test,mae_train,mape_test,mape_train,r2_test,r2_train,rms_test,rms_train
0,LinearRegression,"LinearRegression(copy_X=True, fit_intercept=Tr...",Not Calculated,51.942311,51.777792,61.652823,58.783411,0.198272,0.212148,89.242663,91.827023

### Multiple Linear Regression

In [16]:
import statsmodels.api as sm

C:\Users\sreer\Anaconda3\envs\learn_python\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [17]:
from pandas.core import datetools

#Select response y and Training set X
my_cols = ['lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2', 'NSM']
X = data[my_cols]
y = data['Appliances']

In [18]:
# Building the optimal model 
import statsmodels.formula.api as sm
#X = X.value
model = sm.OLS(y, X).fit()
predictions = model.predict(X)
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:             Appliances   R-squared:                       0.210
Model:                            OLS   Adj. R-squared:                  0.208
Method:                 Least Squares   F-statistic:                     145.1
Date:                Sun, 18 Mar 2018   Prob (F-statistic):               0.00
Time:                        18:58:11   Log-Likelihood:            -1.1706e+05
No. Observations:               19735   AIC:                         2.342e+05
Df Residuals:                   19698   BIC:                         2.345e+05
Df Model:                          36
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             1.7462      0.094     18.511      0.000       1.561       1.931
x2             4.7267      1.916      2.466      0.014       0.970       8.483
x3            12.0105      0.683     17.586      0.000      10.672      13.349
x4           -21.8689      1.610    -13.582      0.000     -25.025     -18.713
x5           -13.0846      0.762    -17.175      0.000     -14.578     -11.591
x6            24.0234      1.088     22.090      0.000      21.892      26.155
x7             7.5056      0.689     10.888      0.000       6.154       8.857
x8            -0.8593      1.055     -0.815      0.415      -2.927       1.208
x9            -2.4040      0.639     -3.759      0.000      -3.657      -1.151
x10           -0.4272      1.176     -0.363      0.716      -2.733       1.878
x11            0.0811      0.086      0.939      0.348      -0.088       0.250
x12            2.1878      0.680      3.217      0.001       0.855       3.521
x13           -0.1903      0.080     -2.390      0.017      -0.346      -0.034
x14            3.0506      1.308      2.332      0.020       0.486       5.615
x15           -1.3978      0.430     -3.252      0.001      -2.240      -0.555
x16            9.0849      0.996      9.120      0.000       7.132      11.037
x17           -1.3936      0.400     -3.480      0.001      -2.178      -0.609
x18          -15.3987      1.864     -8.262      0.000     -19.052     -11.746
x19           -0.1147      0.442     -0.260      0.795      -0.981       0.752
x20           -2.4207      1.544     -1.568      0.117      -5.446       0.605
x21            0.1876      0.105      1.784      0.074      -0.018       0.394
x22            0.5522      0.318      1.735      0.083      -0.072       1.176
x23            1.2973      0.345      3.757      0.000       0.621       1.974
x24            0.1375      0.057      2.431      0.015       0.027       0.248
x25            0.9414      1.460      0.645      0.519      -1.920       3.803
x26         8.911e-06   3.92e-05      0.227      0.820    -6.8e-05    8.58e-05
x27           -1.6728      0.479     -3.493      0.000      -2.612      -0.734
x28          -54.2819     21.602     -2.513      0.012     -96.624     -11.939
x29          -64.0214     21.631     -2.960      0.003    -106.420     -21.623
x30          -32.0322     21.571     -1.485      0.138     -74.313      10.248
x31          -86.2711     21.677     -3.980      0.000    -128.759     -43.783
x32           -2.0124      5.035     -0.400      0.689     -11.881       7.856
x33           -7.1199      5.120     -1.391      0.164     -17.155       2.915
x34          -15.6129      9.603     -1.626      0.104     -34.435       3.209
x35          -35.0456      9.801     -3.576      0.000     -54.256     -15.835
x36          -18.4794      4.974     -3.715      0.000     -28.229      -8.729
x37          -22.1231      5.058     -4.374      0.000     -32.036     -12.210
x38          -17.9098      5.060     -3.539      0.000     -27.829      -7.991
x39          -67.6447     23.969     -2.822      0.005    -114.627     -20.663
x40          -50.6585     19.235     -2.634      0.008     -88.361     -12.956
x41          -54.9968     21.629     -2.543      0.011     -97.391     -12.603
x42          -63.3064     21.674     -2.921      0.003    -105.789     -20.824
==============================================================================
Omnibus:                    13905.173   Durbin-Watson:                   0.657
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           215687.216
Skew:                           3.289   Prob(JB):                         0.00
Kurtosis:                      17.799   Cond. No.                     1.15e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.69e-19. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [19]:
X.shape

(19735, 42)

## Decision Tree Classifier

#Select response y and Training set X
my_cols = ['lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2', 'NSM']
X = data[my_cols]
y = data['Appliances']

In [20]:
from sklearn import tree
cltree = tree.DecisionTreeClassifier()

In [21]:

X = data[my_cols]
y = data['Appliances']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)
dtc = cltree.fit(X_train, y_train)

In [22]:
evaluate_model(dtc, "DecisionTreeClassifier",dtc,X_train,y_train, X_test , y_test)

,Model_desc,Model_param,cross_val_score,mae_test,mae_train,mape_test,mape_train,r2_test,r2_train,rms_test,rms_train
0,LinearRegression,"LinearRegression(copy_X=True, fit_intercept=Tr...",Not Calculated,51.942311,51.777792,61.652823,58.783411,0.198272,0.212148,89.242663,91.827023
0,DecisionTreeClassifier,"DecisionTreeClassifier(class_weight=None, crit...",Not Calculated,35.618160,0.000000,33.043778,0.000000,0.239412,1.000000,86.922802,0.000000

### RandomForest

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
#splitting dataset into training and Test set
from sklearn.model_selection import train_test_split
X = data[my_cols]
y = data['Appliances']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)
dtc = cltree.fit(X_train, y_train)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.75, test_size = 0.25)

In [44]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [45]:
#Fitting Random Forest Regressor to the Training set
from sklearn.ensemble import RandomForestRegressor
classifier = RandomForestRegressor(n_estimators = 300,  random_state=0,max_features=4 )
classifier.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features=4, max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=300, n_jobs=1, oob_score=False, random_state=0,
           verbose=0, warm_start=False)

In [46]:
evaluate_model(classifier, "RandomForestRegressor",classifier,X_train,y_train, X_test , y_test)

,Model_desc,Model_param,cross_val_score,mae_test,mae_train,mape_test,mape_train,r2_test,r2_train,rms_test,rms_train
0,LinearRegression,"LinearRegression(copy_X=True, fit_intercept=Tr...",Not Calculated,51.942311,51.777792,61.652823,58.783411,0.198272,0.212148,89.242663,91.827023
0,RandomForestRegressor,"(DecisionTreeRegressor(criterion='mse', max_de...",Not Calculated,29.479290,11.197177,28.454792,10.787280,0.603533,0.943694,63.805882,24.420606

### XG Boost

In [ ]:
import xgboost as xgb
from xgboost import XGBClassifier

In [ ]:
#splitting dataset into training and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.75, test_size = 0.25)

In [ ]:
#fit model on training data
XGB = XGBClassifier()
XGB.fit(X_train, y_train)

In [ ]:
evaluate_model(XGB, "XGBClassifier",XGB,X_train,y_train, X_test , y_test)

## Gradient Boosting Model

In [ ]:
# Gradient Boosting Model

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import MinMaxScaler

In [ ]:
X = data[my_cols]
y = data['Appliances']
min_max_scaler = MinMaxScaler()
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.75, test_size = 0.25)
Classifier = GradientBoostingClassifier(n_estimators = 25, random_state = 0, max_features = 3, verbose = 1)
Classifier.fit(X_train, y_train)

In [ ]:
evaluate_model(Classifier, "GradientBoostingClassifier",Classifier,X_train,y_train, X_test , y_test)

## K Means

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
X = data[my_cols]
y = data['Appliances']
# min_max_scaler = MinMaxScaler()
# X = min_max_scaler.fit_transform(X)
# y = min_max_scaler.fit_transform(y.reshape(1, -1))
X_train, X_test, y_train, y_test = train_test_split(X, y,train_size=0.75, test_size=0.25)
classifier = KMeans(n_clusters=2, n_jobs=-1, verbose=1 )
classifier.fit(X_train, y_train)

In [ ]:
evaluate_model(classifier, "Kmeans",classifier,X_train,y_train, X_test , y_test)

## Keras Tensorflow

In [ ]:

from math import sqrt
from numpy import concatenate
from matplotlib import pyplot
from pandas import read_csv
from pandas import DataFrame
from pandas import concat
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

In [ ]:
X = data[my_cols].values
y = data['Appliances']
min_max_scaler = MinMaxScaler()
X = min_max_scaler.fit_transform(X)
# split into train and test sets
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.25, random_state = 0)


# reshape input to be 3D [samples, timesteps, features]


train_X = train_X.reshape((train_X.shape[0], 1, train_X.shape[1]))
test_X = test_X.reshape((test_X.shape[0], 1, test_X.shape[1]))
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

In [ ]:
# design network
model = Sequential()
model.add(LSTM(50, input_shape=(train_X.shape[1], train_X.shape[2])))
model.add(Dense(1))
model.compile(loss='mae', optimizer='adam')
# fit network
history = model.fit(train_X, train_y, epochs=10, batch_size=12, validation_data=(test_X, test_y), verbose=2, shuffle=False)
# plot history
plt.plot(history.history['loss'], label='train')
plt.plot(history.history['val_loss'], label='test')
plt.legend()
plt.show()

In [ ]:
yhat = model.predict(test_X)
yhat
rmse = sqrt(mean_squared_error(test_y, yhat))
print('Test RMSE: %.3f' % rmse)
r2_score(test_y, yhat)

In [ ]:
evaluate_model(model, "Keras-LSTM",model,train_X,train_y, test_X , test_y)

## Gradient Boosting Regressor

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor  
from sklearn.cross_validation import LeaveOneLabelOut
from sklearn.grid_search import GridSearchCV
import operator
from math import sqrt

In [ ]:
gbr=GradientBoostingRegressor(n_estimators= 300,learning_rate = 1.0, max_features= 'sqrt') 

# min_max_scaler = MinMaxScaler()
# X = min_max_scaler.fit_transform(X)
# split into train and test sets


train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.25, random_state = 0)

gbr.fit(train_X, train_y)
y_pred=gbr.predict(test_X) 

print ("R-squared for Train: %.2f" %gbr.score(train_X, train_y))
print ("R-squared for Test: %.2f" %gbr.score(test_X, test_y))

In [ ]:
def GB(param_grid): 
    estimator = GradientBoostingRegressor()
    cv = LeaveOneLabelOut(train_X.shape)
    classifier = GridSearchCV(estimator=estimator, cv=cv, param_grid=param_grid, n_jobs=-1) 
    classifier.fit(train_X, train_y)
    classifier.best_estimator_ 
    return classifier.best_estimator_

In [ ]:
param={'n_estimators':[300], 
            'learning_rate': [0.1],
            'max_depth':[6], 
            'min_samples_leaf':[5],
            'max_features':[1.0]
           } 
estimation=GB(param)

In [ ]:
evaluate_model(estimation, "GradientBoostingRegressor",estimation,train_X,train_y, test_X , test_y)

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()
X = min_max_scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y,train_size=0.75, test_size=0.25)

mlp = MLPClassifier(hidden_layer_sizes=(37,37,37))
mlp.fit(X_train,y_train)

In [ ]:
evaluate_model(mlp, "mlp",mlp,X_train,y_train, X_test , y_test)

## Logistic Regression

In [ ]:
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [ ]:
validation_size = 0.20
min_max_scaler = MinMaxScaler()
X = min_max_scaler.fit_transform(X)
# split into train and test sets
X = X.values
y = data['Appliances']
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, y, test_size=validation_size, random_state=seed)

In [ ]:
seed = 2
scoring = 'accuracy'

In [ ]:
models = []
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
# models.append(('SVM', SVC()))
# evaluate each model in turn
results = []
names = []
for name, model in models:
    kfold = model_selection.KFold(n_splits=2, random_state=seed)
    cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='r2')
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)

In [ ]:
# Compare Algorithms
fig = plt.figure(figsize=(20,10))
fig.suptitle('Algorithm Comparison')
ax = fig.add_subplot(111)
plt.boxplot(results)
ax.set_xticklabels(names)
plt.show()